name: update site data

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: node scripts/getReleasesInformation.mjs
      - run: node scripts/getRepoInformation.mjs
      - run: |
          git add orgContributors.json
          git add releases.json
          git diff --quiet && git diff --staged --quiet || git commit -m "[:robot: BOT] Update orgContributors.json and releases.json"
          git push origin main
